version: '2'
services:
  server:
    image: thann/feedback  # x86
    #build:
    #  context: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - db:/usr/src/app/db
    # Handy for dev
    #  - ./api:/usr/src/app/api
    #  - ./webapp:/usr/src/app/webapp
    #  - ./test:/usr/src/app/test
    #  - ./lib:/usr/src/app/lib
    #  - ./db:/usr/src/app/db
    #command: server --dev


volumes:
  db:
